# Generated by Django 4.1 on 2023-03-30 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import route.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(default=route.models.generate_account_number, max_length=8, unique=True)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('loan', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
