# Generated by Django 4.1 on 2023-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='loan',
            new_name='APE',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='Btc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='Eth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='Ltc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='ShB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='TRX',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
