# Generated by Django 4.1 on 2023-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_rename_loan_account_ape_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='SAD',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
