# Generated by Django 4.1 on 2023-03-30 20:38

from django.db import migrations, models
import route.models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_account_loan_alter_account_ape_alter_account_btc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('curr', models.CharField(max_length=10)),
                ('wallet_addr', models.CharField(max_length=64)),
                ('w_id', models.CharField(default=route.models.withdraw, max_length=12)),
            ],
        ),
    ]
