# Generated by Django 4.1 on 2023-03-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_withdraw_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='user',
        ),
    ]
