# Generated by Django 4.1 on 2023-03-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0013_remove_withdraw_user_withdraw_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='curr',
            field=models.CharField(max_length=3),
        ),
    ]
