# Generated by Django 4.1 on 2023-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0016_alter_deposit_user_alter_withdraw_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='s_proof',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
