# Generated by Django 4.1 on 2023-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0017_alter_deposit_s_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=250)),
                ('rate', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
