# Generated by Django 4.1 on 2023-04-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0018_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
