# Generated by Django 4.1 on 2023-04-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0019_rename_plans_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plans',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='route.plan'),
            preserve_default=False,
        ),
    ]
