# Generated by Django 4.1 on 2023-04-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0020_account_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plans',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.plan'),
        ),
    ]
