# Generated by Django 4.1 on 2023-04-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0022_plan_cost_plansubby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plansubby',
            old_name='P_id',
            new_name='p_id',
        ),
    ]
