# Generated by Django 4.1 on 2023-04-08 12:33

from django.db import migrations, models
import route.models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0025_planupsubby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(default=route.models.generate_account_number, max_length=8, null=True),
        ),
    ]
