# Generated by Django 4.1 on 2023-04-08 18:48

from django.db import migrations, models
import django.db.models.deletion
import route.models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0026_alter_account_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(default=route.models.generate_account_number, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='plans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.plan'),
        ),
    ]
