# Generated by Django 4.1 on 2023-04-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0027_alter_account_acc_no_alter_account_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='APE',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Btc',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Eth',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Ltc',
        ),
        migrations.RemoveField(
            model_name='account',
            name='SAD',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ShB',
        ),
        migrations.RemoveField(
            model_name='account',
            name='TRX',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='curr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.depcurr'),
        ),
    ]
