# Generated by Django 4.1 on 2023-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0028_depcurr_remove_account_ape_remove_account_btc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
