# Generated by Django 4.1 on 2023-04-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0032_alter_deposit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
