# Generated by Django 4.1 on 2023-04-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0035_alter_deposit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tran', models.CharField(max_length=45)),
                ('amount', models.FloatField(default=0)),
                ('transaction_id', models.CharField(max_length=45)),
                ('date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('amount', models.FloatField(default=0)),
                ('mode', models.CharField(max_length=45)),
                ('date', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.plan')),
            ],
        ),
    ]
