# Generated by Django 4.1 on 2023-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0038_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='name',
            field=models.CharField(default='ff', max_length=45),
            preserve_default=False,
        ),
    ]
