# Generated by Django 4.1 on 2023-04-24 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0042_alter_deposit_curr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='curr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.depcurr'),
        ),
    ]
